### ISSUE TITLE
Calendar / time modal

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#1]
When entering in date time be able to do some from a calendar modal button opposed to typing correct syntax /import export

**Comment by EagleAglow** [comment]
I'll look at: https://www.itsolutionstuff.com/post/how-to-use-bootstrap-datepicker-in-laravelexample.html

**Comment by EagleAglow** [comment]
Changed input field type to "date" on: ./resources/views/admins/schedules/edit.blade.php
