### ISSUE TITLE
Adding a "view full schedule" button

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#11]
When viewing the schedule during the bid for example if you are not the active bidder a user can login to view/tag lines and click the later button to view dates of that schedule down the road.

An active bidder when logged in can click bid and after hitting bid the user is presented with the entire schedule in condensed view before confirming the bid.

Essentially what I am looking to add is a view full schedule button which will allow a non-active bidder/active bidder to see that full lines schedule in the exact same manner regardless if they are active bidder or not without having to bid to do so

**Comment by EagleAglow** [comment]
Added "Show" button
