### ISSUE TITLE
Feature req: Bid Status on bidder end

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#12]
Vision : logged in bidder able to click or see at first glance e.g.

X AMOUNT of Bidders left ahead of you
Something like that a bit more articulate though. Don't know if particulate elements on a page such as this could be refreshed on some kind of timer either?

**Comment by EagleAglow** [comment]
Bidder dashboard shows the bidder their bidder order number, and the next bidder order number.  Added dashboard for supervisor / admin to track bidding progress.  Currently "401" access denied for bidders - could be changed.
