### ISSUE TITLE
Mass sms/email

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#15]
Ability to send out a particular sms/email to all users/specific users with either or but specifically sent individually e.g. Not seeing other users numbers or emails in sent message.

I found two references for laravel and twilio in this regard for the sms side at least

https://www.twilio.com/blog/send-bulk-sms-twilio-laravel-php
https://www.twilio.com/blog/create-sms-portal-laravel-php-twilio

**Comment by EagleAglow** [comment]
Can now create and send individual texts to all users with phone numbers (others are skipped). Can now create and send individual  emails to all users.  Feature is on Settings page - may be moved, eventually.
