### ISSUE TITLE
Manual Re-sending of notifications on a paused bid

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#16]
In a hypothetical scenario where bidding is paused and say resumed following day for example. Would it be possible on the manage bidding screen to have a button which when clicked would resend the active bidder next bidder notifications via email and or text to the users flagged as such or maybe just built in within the pause/start function to do this by default?

**Comment by EagleAglow** [comment]
New notifications to next bidders now happens (in addition to original notification) when bidding continues after pause.
