### ISSUE TITLE
Changing the order of chosen schedule line

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#2]
Current display indicates particular shift code and which dates you work said shift code in sequential order. Would it be possible for this to just straight up display schedule in complete linear fashion? e.g.

Jan 1 - shift
Jan 2 - shift
Jan 3 - day off etc

**Comment by EagleAglow** [comment]
Current version has repeated cycles, like:
Jan 1, Mar25, May 23 - shift
Jan 2, Mar 26, May 24, etc

Makes page compact. Sequence is available on print or ics file down load.
