### ISSUE TITLE
On schedule print page 

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#3]
In addition to the printing of a schedule, ability to also download /open an iCal/ics file which user can download /open on their phone importing said schedule into Android / iPhone calendar?

**Comment by EagleAglow** [comment]
Look at: markuspoerschke/iCal

**Comment by bradtn** [comment]
https://www.a2zwebhelp.com/export-data-to-ics

**Comment by EagleAglow** [comment]
ics file is attached to email notification of bid selected.

**Comment by EagleAglow** [comment]
Added download button for ics file to successful bidder page
