### ISSUE TITLE
Feature request: shifting tagged lines to top of line list in tag order 

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#6]
Currently tagging works as intended will show a user who has pretagged lines which ones they tagged denoted with a star. When there are a lot of lines might take some sifting through would be nice if possible anyways to have said tagged lines re arranged to top of line list / first page for easier access and quicker viewing etc.

**Comment by EagleAglow** [comment]
Bidding page shows preferred (tagged) lines in order of preference, followed by remaining available lines.  Optional sort order shows all.
