### ISSUE TITLE
Feature req: emailing users during bidding

### ISSUE THREAD

**Issue by bradtn** [EagleAglow/SBS-web#9]
Emailing current active bidder informing them they are up.

Emailing next up to the bidder informing them they are next

Possibly need to add two spots for email in this regard work/personal

**Comment by EagleAglow** [comment]
Feature to Email to next bidder added.  "Next to next" not yet.

**Comment by EagleAglow** [comment]
When bidder notification is set on (text and/or email), the "next" bidder gets a "heads up" message when the new current/active bidder is told that they can bid.
